### ISSUE TITLE
Add full support to T16 / T19 - Time and light flash

### ISSUE THREAD

**Issue by fazioa** [souliss/bindingopenhab#3]
-  21(hex) as command, the light flash on and off at each cycle
- >30(hex) as command, time the output to ON

**Comment by fazioa** [comment]
...and for T19 
-  21(hex) as command, the light flash on and off at each cycle
-  22(hex) as command, set the intensity
- >30(hex) as command, time the output to ON

**Comment by Yonathan1982** [comment]
Testing the T19 in openhab and souliss , the update does not work states, some commands as if they lit but then turns off.

**Comment by juanpintom** [comment]
I tested this too, If you set the brightness manually on Souliss the value isn't updated on OH side.

**Comment by fazioa** [comment]
Note: T19

03:03:35.560 [INFO ] [runtime.busevents             :22   ] - display received command 82
03:03:35.560 [INFO ] [.o.b.s.internal.SoulissBinding:142  ] - receiveCommand - display = 82 - Typical: 0x19
03:03:35.560 [DEBUG] [.s.i.n.typicals.StateTraslator:68   ] - translate commands: 82 -> null

!ENTRY org.eclipse.equinox.event 4 0 2015-09-30 03:03:35.561
!MESSAGE Exception while dispatching event org.osgi.service.event.Event [topic=openhab/command/display] to handler org.openhab.binding.souliss.internal.SoulissBinding@677edeff
!STACK 0
java.lang.NullPointerException
    at org.openhab.binding.souliss.internal.SoulissBinding.receiveCommand(SoulissBinding.java:193)
    at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:42)
    at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
    at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
    at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
    at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)

**Comment by fazioa** [comment]
Binding update correctly T19 value, but don't respond to slider

Configuration:
.items
Number display "Display [%.1f %%]"  (TechnicView_Node1) {souliss="T19:1:9"}

.sitemap
Slider item=display

**Comment by fazioa** [comment]
Bug fix: https://drive.google.com/drive/u/0/folders/0BzyjHRwlzov4WlgtSG0tejJ3aE0
File: org.openhab.binding.souliss_1.7.0.201510012359 (current).jar

TEST IT PLEASE

Configuration:
.items
Number display "Display [%.1f %%]" (TechnicView_Node1) {souliss="T19:1:9"}
OR
Dimmer display "Display [%.1f %%]"  (TechnicView_Node1) {souliss="T19:1:9"}

.sitemap
Slider item=display
OR
Setpoint item=display step=1 minValue=0 maxValue=100
OR
Setpoint item=display step=10 minValue=0 maxValue=100

**Comment by fazioa** [comment]
TODO: Add support to commands:

#define Souliss_T1n_OnCmd           0x02
#define Souliss_T1n_OffCmd          0x03
#define Souliss_T1n_BrightUp        0x10
#define Souliss_T1n_BrightDown      0x20
#define Souliss_T1n_Flash           0x21
#define Souliss_T1n_Timed           0x30

**Comment by jdevine82** [comment]
Hi fazioa
just wondering if you have added support to T19 Bright Up and down? I can see i think where to add to code but have not idea how to compile the jar file... Have you already done this?

**Comment by jdevine82** [comment]
I tried the above file from your google drive and the slider increment implementation works for T19 but also seemed to break support for T12 on off control...

**Comment by fazioa** [comment]
I don't understand. Do you found a bug in T12?
Il 10/gen/2016 02:13, "jdevine82" notifications@github.com ha scritto:

**Comment by jdevine82** [comment]
I mean t12 was working but t 19 wasn't then I changed to https://drive.google.com/drive/u/0/folders/0BzyjHRwlzov4WlgtSG0tejJ3aE0 and now t19 works but t12 dosent...

**Comment by dariocdj** [comment]
Escuse me @fazioa  but with https://drive.google.com/drive/u/0/folders/0BzyjHRwlzov4WlgtSG0tejJ3aE0 T19 work and with new openhab included binding 1.7.1 it gives me this error in loop : 
Error while executing background thread Souliss Refresh Service
java.lang.IllegalArgumentException: Value must be between 0 and 100
 at org.openhab.core.library.types.PercentType.validateValue(PercentType.java:48) ~[na:na]
        at org.openhab.core.library.types.PercentType.<init>(PercentType.java:38) ~[na:na]
        at org.openhab.binding.souliss.internal.network.typicals.SoulissT19.getOHState(SoulissT19.java:78) ~[na:na]
        at org.openhab.binding.souliss.internal.network.typicals.Monitor.check(Monitor.java:112) ~[na:na]
        at org.openhab.binding.souliss.internal.network.typicals.Monitor.tick(Monitor.java:51) ~[na:na]
        at org.openhab.binding.souliss.internal.SoulissBinding.execute(SoulissBinding.java:343) ~[na:na]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]

What's happenned ? 
sitemap : 
//      Slider item=D3Node1
//      Slider item=D3Node2
        Slider item=D3Node1 step=10 minValue=0 maxValue=100
        Slider item=D3Node2 step=10 minValue=0 maxValue=100

items : 
Dimmer  D3Node1 "Led Living [%.1f %%]" (grp1, gTechnicView_Node2)  {souliss="T19:2:0"}
Dimmer  D3Node2 "Led Lato Pranzo [%.1f %%]"  (grp1, gTechnicView_Node2)  {souliss="T19:2:2"}

What's wrong ?
thanks
Dario2

**Comment by fazioa** [comment]
Try to use last version in Google drive.
Il 01/mar/2016 01:08, "Dario" notifications@github.com ha scritto:
